# Copyright 2018 The Openstack-Helm Authors.
# Copyright (c) 2018 AT&T Intellectual Property. All rights reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

---
specs:
    # Source MTN_57_AEC_Design_Specs_v_1.1.xlsx
    spec1:
        header_row: 2
        ipmi_address_header: 'IPMI Address'
        ipmi_sheet_name: '6.0 Server IP-Profile Info'
        start_row: 3
        end_row: 22
        hostname_col: 1
        ipmi_address_col: 3
        host_profile_col: 5
        ipmi_gateway_col: 4
        private_ip_sheet: 'Private IPs'
        net_type_col: 1
        net_vlan_col: 2
        net_start_row: 2
        net_end_row: 13
        subnet_col: 3
        cidr_per_rack_col: 4
        public_ip_sheet: 'Public IPs'
        oam_vlan_col: 1
        oam_ip_row: 3
        oam_ip_col: 2
        ingress_ip_row: 5
        dns_ntp_sheet: '7.0 Build notes'
        ntp_row: 13
        ntp_col: 2
        dns_row: 14
        dns_col: 2
        domain_row: 2
        domain_col: 2
    # Source MTN52_AEC_Eng_Design_Specs_v1.4.xlsx
    spec2:
        header_row: 1
        ipmi_address_header: 'IPMI Address'
        ipmi_sheet_name: '4.IPMI-Host Profile'
        start_row: 2
        end_row: 13
        hostname_col: 1
        ipmi_address_col: 3
        host_profile_col: 5
        ipmi_gateway_col: 4
        private_ip_sheet: 'Private IPs'
        net_type_col: 1
        net_vlan_col: 2
        net_start_row: 3
        net_end_row: 14
        subnet_col: 3
        cidr_per_rack_col: 4
        public_ip_sheet: 'Public IPs'
        oam_vlan_col: 1
        oam_ip_row: 4
        oam_ip_col: 2
        ingress_ip_row: 6
        dns_ntp_sheet: '5.0 Build notes'
        ntp_row: 12
        ntp_col: 2
        dns_row: 13
        dns_col: 2
        domain_row: 1
        domain_col: 2
    # Source MTN54_AEC_Eng_Design_Specs_v1.2.xlsx
    spec3:
        header_row: 2
        ipmi_address_header: 'IPMI Address'
        ipmi_sheet_name: 'Server IP-Profile Info'
        start_row: 3
        end_row: 14
        hostname_col: 1
        ipmi_address_col: 3
        host_profile_col: 5
        ipmi_gateway_col: 4
        private_ip_sheet: 'Private IPs'
        net_type_col: 1
        net_vlan_col: 2
        net_start_row: 2
        net_end_row: 13
        subnet_col: 3
        cidr_per_rack_col: 4
        public_ip_sheet: 'Public IPs'
        oam_vlan_col: 1
        oam_ip_row: 3
        oam_ip_col: 2
        ingress_ip_row: 5
        dns_ntp_sheet: '8.0 Build notes'
        ntp_row: 13
        ntp_col: 2
        dns_row: 14
        dns_col: 2
        domain_row: 2
        domain_col: 2
