##################################
# Site Specific Tugboat Settings #
##################################
---
sitetype: nc
proxy:
    http: 'http://one.proxy.att.com:8080'
    https: 'http://one.proxy.att.com:8080'

no_proxy : '10.96.0.2,10.96.232.136,artifacts-nc.mtn29.cci.att.com,docker-nc.mtn29.cci.att.com,docker-open-nc.mtn29.cci.att.com,10.96.0.1,cluster.local,svc.cluster.local,,localhost,127.0.0.1,10.0.0.0/8'
ceph :
    osd_count : 6
    osd_count_fullsite : 24
    osd : 
    - 'sdc'
    - 'sdd'
    - 'sde'
    - 'sdf' 
    - 'sdg'
    - 'sdh'

hostprofile_interfaces :
    cp:
        networks: 
            bond1: 
                - 'gp_nic01'
                - 'gp_nic02'
            p1p1: 'sriov_nic01'
            p3p2: 'sriov_nic02'
    gv:
        networks: 
            bond1: 
                - 'gp_nic01'
                - 'gp_nic02'
            p1p1: 'sriov_nic01'
            p3p2: 'sriov_nic02'
    nsb:
        networks: 
            pxe: 'eno4'
            bond1: 
                - 'gp_nic01'
                - 'gp_nic02'
            p1p1: 'sriov_nic01'
            p3p2: 'sriov_nic02'
    ns:
        networks: 
            pxe: 'eno4'
            bond1: 
                - 'gp_nic01'
                - 'gp_nic02'
            p1p1: 'sriov_nic01'
            p3p2: 'sriov_nic02'  
bgp :
    peers:
    - '172.29.0.2' 
    - '172.29.0.3'
    asnumber: 64671
    peer_asnumber: 64688

hardware_profile :
    nc :
        host_type :
            ctrl : 'nc-cp'
            compute : 'nc-ns-r740'
        hw_type : 'dell_r740_purley_nc'
        profile_name :
            ctrl : 'cp'
            compute : 'nsb'
        sriov_itf :
             itf1 : 
             - 'p2p2'
             - 'dp_nic01'
             itf2 :
             - 'p7p1'
             - 'dp_nic02'
    5ec :
        host_type : 
            ctrl : '5ec-cp'
            compute : '5ec-ns-r640'
        hw_type : 'dell_r640_purley_5ec'
        profile_name :
            ctrl : 'cp'
            compute : 'nsb'
        sriov_itf :
             itf1 : 
             - 'p1p1'
             - 'sriov_nic01'
             itf2 :
             - 'p3p2'
             - 'sriov_nic02'
conf :
    nova:
        vcpu_pin_set : '4-43,48-55'
        passthrough_whitelist :
            - physical_network : "sriovnet2"
              address : "0000:d8:0a.0"
              trusted : "true"
            - physical_network : "sriovnet2"
              address : "0000:d8:0a.1"
              trusted : "true"
            - physical_network : "sriovnet2"
              address : "0000:d8:0a.2"
              trusted : "true"              
            - physical_network : "sriovnet2"
              address : "0000:d8:0a.3"
              trusted : "true"                
            - physical_network : "sriovnet2"
              address : "0000:d8:0a.4"
              trusted : "true"              
            - physical_network : "sriovnet2"
              address : "0000:d8:0a.5"
              trusted : "true"
            - physical_network : "sriovnet2"
              address : "0000:d8:0a.6"
              trusted : "true"                
            - physical_network : "sriovnet2"
              address : "0000:d8:0a.7"
              trusted : "true"  
            - physical_network : "sriovnet2"
              address : "0000:3b:02.0"
              trusted : "true"
            - physical_network : "sriovnet2"
              address : "0000:3b:02.1"
              trusted : "true"
            - physical_network : "sriovnet2"
              address : "0000:3b:02.2"
              trusted : "true"              
            - physical_network : "sriovnet2"
              address : "0000:3b:02.3"
              trusted : "true"     
            - physical_network : "sriovnet2"
              address : "0000:3b:02.4"
              trusted : "true"  
            - physical_network : "sriovnet2"
              address : "0000:3b:02.5"
              trusted : "true"              
            - physical_network : "sriovnet2"
              address : "0000:3b:02.6"
              trusted : "true"     
            - physical_network : "sriovnet2"
              address : "0000:3b:02.7"
              trusted : "true"  
            - physical_network : "sriovnet2"
              address : "0000:3b:03.0"
              trusted : "true"
            - physical_network : "sriovnet2"
              address : "0000:3b:03.1"
              trusted : "true"              
            - physical_network : "sriovnet2"
              address : "0000:3b:03.2"
              trusted : "true"
            - physical_network : "sriovnet2"
              address : "0000:3b:03.3"
              trusted : "true"
            - physical_network : "sriovnet2"
              address : "0000:3b:03.4"
              trusted : "true"
            - physical_network : "sriovnet2"
              address : "0000:3b:03.5"
              trusted : "true"
            - physical_network : "sriovnet2"
              address : "0000:3b:03.6"
              trusted : "true"
            - physical_network : "sriovnet2"
              address : "0000:3b:03.7"
              trusted : "true"
            - physical_network : "sriovnet2"
              address : "0000:3b:04.0"
              trusted : "true"
            - physical_network : "sriovnet2"
              address : "0000:3b:04.1"
              trusted : "true"       
            - physical_network : "sriovnet2"
              address : "0000:3b:04.2"
              trusted : "true"
            - physical_network : "sriovnet2"
              address : "0000:3b:04.3"
              trusted : "true"      
            - physical_network : "sriovnet2"
              address : "0000:3b:04.4"
              trusted : "true"
            - physical_network : "sriovnet2"
              address : "0000:3b:04.5"
              trusted : "true"
            - physical_network : "sriovnet2"
              address : "0000:3b:04.6"
              trusted : "true"
            - physical_network : "sriovnet2"
              address : "0000:3b:04.7"
              trusted : "true"
            - physical_network : "sriovnet2"
              address : "0000:3b:05.0"
              trusted : "true"
            - physical_network : "sriovnet2"
              address : "0000:3b:05.1"
              trusted : "true"       
            - physical_network : "sriovnet2"
              address : "0000:3b:05.2"
              trusted : "true"
            - physical_network : "sriovnet2"
              address : "0000:3b:05.3"
              trusted : "true"      
            - physical_network : "sriovnet2"
              address : "0000:3b:05.4"
              trusted : "true"
            - physical_network : "sriovnet2"
              address : "0000:3b:05.5"
              trusted : "true"
            - physical_network : "sriovnet2"
              address : "0000:3b:05.6"
              trusted : "true"
            - physical_network : "sriovnet2"
              address : "0000:3b:05.7"
              trusted : "true"
            - physical_network : "sriovnet2"
              address : "0000:d8:0b.0"
              trusted : "true"
            - physical_network : "sriovnet2"
              address : "0000:d8:0b.1"
              trusted : "true"                
            - physical_network : "sriovnet2"
              address : "0000:d8:0b.2"
              trusted : "true"
            - physical_network : "sriovnet2"
              address : "0000:d8:0b.3"
              trusted : "true"
            - physical_network : "sriovnet2"
              address : "0000:d8:0b.4"
              trusted : "true"
            - physical_network : "sriovnet2"
              address : "0000:d8:0b.5"
              trusted : "true"
            - physical_network : "sriovnet2"
              address : "0000:d8:0b.6"
              trusted : "true"
            - physical_network : "sriovnet2"
              address : "0000:d8:0b.7"
              trusted : "true"
            - physical_network : "sriovnet2"
              address : "0000:d8:0c.0"
              trusted : "true"
            - physical_network : "sriovnet2"
              address : "0000:d8:0c.1"
              trusted : "true"
            - physical_network : "sriovnet2"
              address : "0000:d8:0c.2"
              trusted : "true"
            - physical_network : "sriovnet2"
              address : "0000:d8:0c.3"
              trusted : "true"
            - physical_network : "sriovnet2"
              address : "0000:d8:0c.4"
              trusted : "true"
            - physical_network : "sriovnet2"
              address : "0000:d8:0c.5"
              trusted : "true"
            - physical_network : "sriovnet2"
              address : "0000:d8:0c.6"
              trusted : "true"
            - physical_network : "sriovnet2"
              address : "0000:d8:0c.7"
              trusted : "true"
            - physical_network : "sriovnet2"
              address : "0000:d8:0d.0"
              trusted : "true"              
            - physical_network : "sriovnet2"
              address : "0000:d8:0d.1"
              trusted : "true"
            - physical_network : "sriovnet2"
              address : "0000:d8:0d.2"
              trusted : "true"
            - physical_network : "sriovnet2"
              address : "0000:d8:0d.3"
              trusted : "true"
            - physical_network : "sriovnet2"
              address : "0000:d8:0d.4"
              trusted : "true"
            - physical_network : "sriovnet2"
              address : "0000:d8:0d.5"
              trusted : "true"
            - physical_network : "sriovnet2"
              address : "0000:d8:0d.6"
              trusted : "true"
            - physical_network : "sriovnet2"
              address : "0000:d8:0d.7"
              trusted : "true"
            - physical_network : "sriovnet2"
              address : "0000:d8:0d.0"
              trusted : "true"              
            - physical_network : "sriovnet2"
              address : "0000:d8:0d.1"
              trusted : "true"
            - physical_network : "sriovnet2"
              address : "0000:d8:0d.2"
              trusted : "true"
            - physical_network : "sriovnet2"
              address : "0000:d8:0d.3"
              trusted : "true"
            - physical_network : "sriovnet2"
              address : "0000:d8:0d.4"
              trusted : "true"
            - physical_network : "sriovnet2"
              address : "0000:d8:0d.5"
              trusted : "true"
            - physical_network : "sriovnet2"
              address : "0000:d8:0d.6"
              trusted : "true"
            - physical_network : "sriovnet2"
              address : "0000:d8:0d.7"
              trusted : "true"   
    neutron:
        network_vlan_ranges: ' oam:100:1000,sriovnet1:105:109,sriovnet2:121:124'
...

