##################################
# Site Specific Tugboat Settings #
##################################
---
site_info:
  ldap:
    common_name: Test_Users
    url: ldap://example.com
    subdomain: testitservices
  ntp:
    servers: 10.10.10.10,20.20.20.20,30.30.30.30
  sitetype: dummy
  domain: SAMPLE.example.com
  dns:
    servers: 10.10.10.10,20.20.20.20,30.30.30.30
network:
  vlan_network_data:
    ingress:
        subnet:
        - 132.68.226.72/29
  bgp :
    peers:
    - '172.29.0.2'
    - '172.29.0.3'
    asnumber: 64671
    peer_asnumber: 64688
storage:
  ceph:
    controller:
      osd_count: 6
...


