###########################
# Global Tugboat Settings #
###########################
---
#Rule_1
ips_to_leave: 12
oob_ips_to_leave: 10
gateway_offset : 1

#Rule_2
deployment_manifest : 'full-site'

#Rule_3
hostprofile_interfaces :
    cp:
        networks: 
            bond1: 
                - 'gp_nic01'
                - 'gp_nic02'
            p1p1: 'sriov_nic01'
            p3p2: 'sriov_nic02'
    gv:
        networks: 
            bond1: 
                - 'gp_nic01'
                - 'gp_nic02'
            p1p1: 'sriov_nic01'
            p3p2: 'sriov_nic02'
    nsb:
        networks: 
            pxe: 'eno4'
            bond1: 
                - 'gp_nic01'
                - 'gp_nic02'
            p1p1: 'sriov_nic01'
            p3p2: 'sriov_nic02'
    ns:
        networks: 
            pxe: 'eno4'
            bond1: 
                - 'gp_nic01'
                - 'gp_nic02'
            p1p1: 'sriov_nic01'
            p3p2: 'sriov_nic02'  

#Rule_4
hardware_profile :
    cruiser :
        host_type :
            ctrl : 'nc-cp'
            compute : 'nc-ns-r740'
        hw_type : 'dell_r740_purley_nc'
        profile_name :
            ctrl : 'cp'
            compute : 'nsb'
        sriov_itf :
             itf1 :
             - 'p2p2'
             - 'dp_nic01'
             itf2 :
             - 'p7p1'
             - 'dp_nic02'

    nc :
        host_type :
            ctrl : 'nc-cp'
            compute : 'nc-ns-r740'
        hw_type : 'dell_r740_purley_nc'
        profile_name :
            ctrl : 'cp'
            compute : 'nsb'
        sriov_itf :
             itf1 : 
             - 'p2p2'
             - 'dp_nic01'
             itf2 :
             - 'p7p1'
             - 'dp_nic02'
    5ec :
        host_type : 
            ctrl : '5ec-cp'
            compute : '5ec-ns-r640'
        hw_type : 'dell_r640_purley_5ec'
        profile_name :
            ctrl : 'cp'
            compute : 'nsb'
        sriov_itf :
             itf1 : 
             - 'p1p1'
             - 'sriov_nic01'
             itf2 :
             - 'p3p2'
             - 'sriov_nic02'


...
