###########################
# Global Rules            #
###########################
#Rule1:  ip_alloc_offset
#        Specifies the number of ip addresses
#        to offset from subnet allocation pool
#        while allocating it to host.
#        for vlan it is set to 12 as default.
#        for oob it is 10
#        for all gateway ip addresss it is set
#        to 1.
#Rule2:  host_profile_interfaces.
#        Specifies the network interfaces type and
#        and their names for a particular hw profile
#Rule3: hardware_profile
#       This specifies the profile details  bases on sitetype.
#       It specifies the profile name and host type for compute,
#       controller along with hw type
---
rule1:
  name: ip_alloc_offset
  ip_alloc_offset:
    default: 12
    oob: 10
    gw: 1
rule2:
  name: host_profile_interfaces
  host_profile_interfaces:
    gv:
      networks:
        p1p1: sriov_nic01
        bond1:
        - gp_nic01
        - gp_nic02
        p3p2: sriov_nic02
    nsb:
      networks:
        p1p1: sriov_nic01
        bond1:
        - gp_nic01
        - gp_nic02
        pxe: en04
        p3p2: sriov_nic02
    cp:
      networks:
        p1p1: sriov_nic01
        bond1:
        - gp_nic01
        - gp_nic02
        p3p2: sriov_nic02
    ns:
      networks:
        p1p1: sriov_nic01
        bond1:
        - gp_nic01
        - gp_nic02
        pxe: en04
        p3p2: sriov_nic02
rule3:
  name: hardware_profile
  hardware_profile:
    nc:
      profile_name:
        compute: nsb
        ctrl: cp
      host_type:
        compute: nc-ns-r740
        ctrl: nc-cp
      hw_type: dell_r740_purley_nc
    5ec:
      profile_name:
        compute: nsb
        ctrl: cp
      host_type:
        compute: 5ec-ns-r640
        ctrl: 5ec-cp
      hw_type: dell_r640_purley_5ec
    cruiser:
      profile_name:
        compute: nsb
        ctrl: cp
      host_type:
        compute: nc-ns-r740
        ctrl: nc-cp
      hw_type: dell_r740_purley_nc
...
